# Generated by Django 2.0.4 on 2018-05-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pastebin',
            new_name='Paste',
        ),
    ]
