# Generated by Django 2.0.4 on 2018-05-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_auto_20180510_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='language',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JS', 'Javascript'), ('OUTROS', 'Outros')], max_length=40),
        ),
    ]
